Main Implementation

In [24]:
import numpy as py
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.rand(3) * 1e-4
        print(f"Initial weights: {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self, input, weights):
        z = np.dot(input, weights) #z = w1*x1 + w2*x2 + w3*bias
        return np.where(z > 0, 1, 0)        

    def fit(self, X, y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, np.ones((len(self.X),1))] # Add bias term to the input data
        print(f"X with bias:\n{X_with_bias}")

        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error: \n{error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
            print(f"updated weights: \n{self.weights}")
            print("#############\n")

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationFunction(X_with_bias, self.weights)
    

    

Dot Product

In [26]:
import numpy as np

w = np.array([0.1, 0.2, 0.3])
x = np.array([1.0, 2.0, 3.0])
y = np.dot(w, x)
print(y)

1.4


Normal Distribution


In [27]:
random = np.random.seed(42) # Set the seed for reproducibility means that the same random numbers will be generated each time the code is run. This is useful for debugging and testing purposes, as it allows you to get the same results every time you run the code. By setting the seed to a specific value (in this case, 42), you ensure that the sequence of random numbers generated will be the same across different runs of the program.

In [28]:
random_normal = np.random.randn(3)
print(random_normal)

[ 0.49671415 -0.1382643   0.64768854]


In [29]:
random = np.random.rand(3)
print(random)

[0.15601864 0.15599452 0.05808361]


Concatenation

In [30]:
import pandas as pd

data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [31]:
X = AND.drop("y", axis=1) 
y = AND["y"] 
y.to_frame() 

y
0  0
1  0
2  0
3  1

In [36]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

Initial weights: [2.05844943e-06 9.69909852e-05 8.32442641e-05]
X with bias:
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
for epoch: 0
predicted value: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[-0.49999794 -0.49990301 -1.49991676]
#############

for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 2.05844943e-06  9.69909852e-05 -9.99916756e-01]
#############

for epoch: 2
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.50000206  0.50009699 -0.49991676]
#############

for epoch: 3
predicted value: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[ 2.05844943e-06  9.69909852e-05 -1.49991676e+00]
#############

for epoch: 4
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.50000206  0.50009699 -0.99991676]
#############



In [32]:
s1 = X.shape
s2 = y.shape
print(s1)
print(s2)

(4, 2)
(4,)


In [33]:
bias = np.c_[X,  -np.ones((len(X),1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])